### ISSUE TITLE
Charts link is not a valid repo URL for versioned docs

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/turtles-docs#72] opened 2024-03-19 19:51 UTC
Attempting to add the turtles repo using the following command (at [this link](https://docs.rancher-turtles.com/docs/getting-started/install_turtles_operator)) results in an error:

```bash
helm repo add turtles https://charts.rancher-turtles.com
```
Error:
```
Error: looks like "https://charts.rancher-turtles.com" is not a valid chart repository or cannot be reached: failed to fetch https://charts.rancher-turtles.com/index.yaml : 404 Not Found
```

However, using the `https://rancher.github.io/turtles` url seems to work as expected:
```
helm repo add turtles https://rancher.github.io/turtles && helm update
helm repo search turtles
```
Result:
```
turtles/rancher-turtles	0.5.0        	0.5.0      	Rancher Turtles is a extension to Rancher that ...
```

The source of this issue appears to be in the [versioned docs](https://github.com/rancher/turtles-docs/blob/main/versioned_docs/version-0.5/getting-started/install_turtles_operator.md). The [un-versioned docs](https://github.com/rancher/turtles-docs/blob/main/docs/getting-started/install_turtles_operator.md) seem to have the correct link.

**Comment by richardcase** [comment] 2024-03-20 09:08
Thanks for this @MbolotSuse . This was caused by us moving the repo from the sandbox to the rancher org and moving away from a custom domain. This is already fixed in the **Next** version of the docs:

- https://github.com/rancher/turtles-docs/blob/main/docs/getting-started/install_turtles_operator.md?plain=1#L34
- https://docs.rancher-turtles.com/docs/next/getting-started/install_turtles_operator

**Closed** 2024-03-28 09:20 UTC
Labels: area/documentation
